### ISSUE TITLE
ArgumentsAdjuster Name Issue

### ISSUE THREAD

**Issue by aherlihy** [eliben/llvm-clang-samples#10]
Hi!

I am attempting to run these examples on OSX. The compiler I'm using is g++ Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn) and the llvm source is the latest pull from LLVM: LLVM version 3.6.0svn, DEBUG build with assertions, on x86_64-apple-darwin13.4.0. 

I've got everything working, except test_live (test_clang_check.TestClangCheck). All other tests pass.

I'm running into an issue when compiling, in src_clang/ClangCheck.cpp on line 171. There seems to have been an API change with InsertArgumentAdjuster. The compiler suggests I use ArgumentsAdjuster instead, although when I make that change I'm running into the following error: 

src_clang/ClangCheck.cpp:172:67: error: no member named 'BEGIN' in 'clang::tooling::ArgumentsAdjuster'. 

The copy I'm working off of is in https://github.com/aherlihy/llvm-clang-samples/tree/OSX.

Thank you, this is a very cool project!

**Comment by eliben** [comment]
These APIs changed considerably since 2014. Please reopen if there's still an issue
