### ISSUE TITLE
Use only llvm-config in Makefile

### ISSUE THREAD

**Issue by jethrogb** [eliben/llvm-clang-samples#15]
Why don't you just use only llvm-config in the Makefile instead of having to point at many different paths? You just point it to the llvm-config of your LLVM installation and you're set, e.g.:

```
LLVM_CONFIG=llvm-config-3.5
LLVM_CXXFLAGS := `$(LLVM_CONFIG) --cxxflags`
LLVM_LDFLAGS := `$(LLVM_CONFIG) --ldflags --libs --system-libs` 
LLVM_LDFLAGS_NOLIBS := `$(LLVM_CONFIG) --ldflags`
CLANG_INCLUDES := -I`$(LLVM_CONFIG) --includedir`/clang
```

**Comment by eliben** [comment]
I do use `llvm-config`. Note that Clang building is not fully supported by it, which is why the other paths are used.

**Comment by jethrogb** [comment]
Ok, well, "works for me" with a binary distribution of llvm/clang/libclang.

**Comment by eliben** [comment]
@jethrogb did you try vs. a source tree? the layout of includes may be different there
