### ISSUE TITLE
src_clang/matchers_rewriter doesn't matches the for loop in inputs/fact.c

### ISSUE THREAD

**Issue by iluvatar593** [eliben/llvm-clang-samples#19]
matchers_rewriter executable with input file fact.c seems bugged, because it doesn't matches the for loop (it doesn't adds the /* increment */ comment) even if the loop structure in the input file seems fine (starting from 0, comparing with a < and incrementing).

**Comment by eliben** [comment]
Thanks for reporting. The matcher is super sensitive to the exact pattern in the initializer - so I changed `fact.c` to comply.

**Comment by iluvatar593** [comment]
Thanks to you for the very useful repo! And how about matching for initializations in general (like with or without declarations)? (sorry if this is not the right place to talk about it)
