### ISSUE TITLE
Missing CLANG_LIBS for plugin_print_functions.so

### ISSUE THREAD

**Issue by WillYee** [eliben/llvm-clang-samples#20]
$(BUILDDIR)/plugin_print_funcnames.so: $(SRC_CLANG_DIR)/plugin_print_funcnames.cpp  
    $(CXX) $(PLUGIN_CXXFLAGS) $(CXXFLAGS) $(LLVM_CXXFLAGS) $(CLANG_INCLUDES) $^ \  
        $(PLUGIN_LDFLAGS) $(LLVM_LDFLAGS) -o $@  

threw a linker error, fixed by changing to 

$(BUILDDIR)/plugin_print_funcnames.so: $(SRC_CLANG_DIR)/plugin_print_funcnames.cpp  
    $(CXX) $(PLUGIN_CXXFLAGS) $(CXXFLAGS) $(LLVM_CXXFLAGS) $(CLANG_INCLUDES) $^ \  
        $(CLANG_LIBS) $(PLUGIN_LDFLAGS) $(LLVM_LDFLAGS) -o $@

**Comment by eliben** [comment]
This is curious. What platform are you on, and what compiler is that with?

In general on Linux you shouldn't need to link libs into the plugin, as it will find those symbols in the Clang binary that loads it.

Consider this: why link MBs of Clang stuff into each and every small plugin, the symbols are there in Clang anyway, and the plugin does not exist in a vacuum - it's loaded by Clang.
