### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by JinJunho** [eliben/llvm-clang-samples#22]
(On OS X Yosemite 10.10.5) I modified Makefile as below:

LLVM_SRC_PATH := $$HOME/clang-llvm/llvm/
...
LLVM_BUILD_PATH := $$HOME/clang-llvm/build
LLVM_BIN_PATH := $(LLVM_BUILD_PATH)/Debug+Asserts/bin
...
#CXX := g++
CXX := clang++
CXXFLAGS := -fno-rtti -O0 -std=c++11 -g -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS `/Users/junho/clang-llvm/build/Debug+Asserts/bin/llvm-config --cxxflags`

And I got this error after running 'make':

-----------------------------------------------

Using LLVM_SRC_PATH = $HOME/clang-llvm/llvm/
Using LLVM_BUILD_PATH = $HOME/clang-llvm/build
Using LLVM_BIN_PATH = $HOME/clang-llvm/build/Debug+Asserts/bin

-----------------------------------------------
clang++ -fpic -fno-rtti -O0 -std=c++11 -g -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS `/Users/junho/clang-llvm/build/Debug+Asserts/bin/llvm-config --cxxflags`  `$HOME/clang-llvm/build/Debug+Asserts/bin/llvm-config --cxxflags` \
	#	src_llvm/hello_pass.cpp -shared `$HOME/clang-llvm/build/Debug+Asserts/bin/llvm-config --ldflags` -o build/hello_pass.so
clang: error: no input files
make: *** [build/hello_pass.so] Error 1ode 1 (use -v to see invocation)

I would like to know if I did something wrong and how I can solve this problem.

**Comment by Lekensteyn** [comment]
Can you edit your post and put triple backticks around it for formatting? E.g.:

    ```
    your Makefile and output here
    ```

**Comment by eliben** [comment]
I don't officially support building on OSX. Take a look at some of the other issues in the tracker - folks have run into problems and proposed solutions.
