### ISSUE TITLE
cmake build config variables

### ISSUE THREAD

**Issue by unphased** [eliben/llvm-clang-samples#24]
I reckon that my issue is a simple one and I figured it would help to have info on this stuff in this project. I do suppose that this question may be more appropriately asked on mailing lists. Anyway, I really appreciate that llvm-clang-samples is an out-of-the box way to compile some tests that link to the llvm build so that we can smoke test it quickly.

I am new to using cmake to build clang and so I have followed instructions and i ran it like this:

`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ../llvm`

This eventually generated a clang executable weighing in at 1.3GB. Something isn't right with that...

Prior to this I was using the Release+Asserts config using the `--enable-optimized` flag to the `configure` script. This was an earlier trunk revision, 232495, but it is only 81MB in size.

Also this time around it required my linux machine to have more than 5GB of total available memory for some of the linking. Never hit that before, my VM isn't provisioned so heavily... 

So it's clear that I need to change my cmake flags to get me a Release+Asserts build but I don't know how.

**Comment by eliben** [comment]
Debug info weighs a lot.

This isn't a guide to building Clang though, sorry. I suggest you ask on the cfe-dev@ mailing list or StackOverflow.

**Comment by unphased** [comment]
yeah thats fair. i will post back here with my solution when i find it. I am pretty sure at this point that the way to go is to use Release with cmake and set another variable to put asserts inside if desired
