### ISSUE TITLE
OpenMP statements

### ISSUE THREAD

**Issue by gihanmudalige** [eliben/llvm-clang-samples#25]
It is really just a clarification I am seeking here. I was trying to use your code in tooling_sample.cpp to do source to source transformation at OpenMP statements. So using something such as : 

// omp statements.
if (isa<OMPParallelForDirective >(s)) 

But the AST does not report OpenMP statements even if the code has a #pragma omp parallel for
Being very very new to compilers and these tools, I wonder if you can point me at the right direction.

**Comment by eliben** [comment]
I'm not sure how to enable OMP support in Clang - there must be some flag you can pass, but I never tried. I recommend asking on the cfe-dev@ mailing list, if the documentation does not answer the question -- e.g. http://blog.llvm.org/2015/05/openmp-support_22.html
