### ISSUE TITLE
tooling_sample dereferences null

### ISSUE THREAD

**Issue by feresum** [eliben/llvm-clang-samples#26]
It appears that when a function template is never used, its body is set to null (This seems undesirable for a refactoring-type tool...I guess there must be some option to prevent this?). For example, if I have the file

```
template<typename> void a() {}
```

I get the following AST node:

```
|-FunctionTemplateDecl 0xda1e98 <templat.cpp:1:1, col:27> col:25 a
| |-TemplateTypeParmDecl 0xda1ce8 <col:10> col:10 typename
| `-FunctionDecl 0xda1df0 <col:20, col:27> col:25 a 'void (void)'
|   `-<<<NULL>>>
```

So `hasBody` returns true [here](https://github.com/eliben/llvm-clang-samples/blob/master/src_clang/tooling_sample.cpp#L57), but the body is null so it crashes.

**Comment by eliben** [comment]
Can you provide a small input code sample that demonstrates this?

**Comment by feresum** [comment]
`template<typename> void a() {}` is the input code.

**Comment by eliben** [comment]
Ah, sorry I missed that.

Would you like to submit a PR to fix this?

To be honest I don't see it as a huge problem, because the role of these samples is mainly to show how to get everything working together, rather than get too deep into the idiosyncrasies of Clang ASTs. There are many many idiosyncrasies there :-) That said, since this is simple it would be nice to fix.

**Comment by feresum** [comment]
I didn't manage to find a very nice way to fix it. One possibility is to change `f->hasBody()` to `f->hasBody() && !f->isLateTemplateParsed()`. The result of this seems to be that the templated function will be ignored when it is defined, but if it is later instantiated, it is visited and the rewriting transformations applied. So, it does not crash but the results are inconsistent.

**Comment by feresum** [comment]
Now I've found the right way to prevent this problem. `-fno-delayed-template-parsing` should be added to the compiler options.

**Comment by eliben** [comment]
You can send a PR to add this in a clarifying comment in the sample code, perhaps?

**Comment by eliben** [comment]
Closing for now. Send a PR if still interested
