### ISSUE TITLE
A newbie issue: fatal error, header files not found

### ISSUE THREAD

**Issue by Vesion** [eliben/llvm-clang-samples#27]
Hi eliben:

​	I'm so sorry to bother you having a look at my problem.

​	I am a newbie in LLVM development and I'm	 following this [official tutorial](http://llvm.org/docs/tutorial/index.html). Since the tutorial talked very little about how to create a project with a manually written Makefile, so I googled a lot about it, and finally I found this nice sample project you shared. 

​	I downloaded the pre-built binaries from [the official](http://llvm.org/releases/download.html#3.8.0) for my OS X 10.11, and untarred it into $HOME/Workdpace/LLVM380. Then as you mentioned in README, I modified the `build_vs_released_binary.sh` (and I didn't modify your Makefile anywhere) to point to correct directory. However when the script launched, I got a bunch of error messages like this:

```shell
clang-3.8: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk'
clang-3.8In file included from src_llvm/simple_bb_pass.cpp:12:
In file included from /Users/Xiang/Workspace/LLVM380/include/llvm/IR/DataLayout.h:23:
In file included from /Users/Xiang/Workspace/LLVM380/include/llvm/ADT/DenseMap.h:17:
In file included from /Users/Xiang/Workspace/LLVM380/include/llvm/ADT/DenseMapInfo.h:17:
In file included from /Users/Xiang/Workspace/LLVM380/include/llvm/ADT/ArrayRef.h:13:
In file included from /Users/Xiang/Workspace/LLVM380/include/llvm/ADT/Hashing.h:48:
In file included from /Users/Xiang/Workspace/LLVM380/include/llvm/Support/DataTypes.h:35:
In file included from /Users/Xiang/Workspace/LLVM380/bin/../include/c++/v1/cmath:301:
/Users/Xiang/Workspace/LLVM380/bin/../include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>

...blabla (all like header file not found)
```

​	It said that clang cannot find MacOSX10.10.sdk, so I checked my sdk and found it has turned to be MacOSX10.11.sdk. But I cannot figure out how to let clang use the MacOSX10.11.sdk and why those header files not found. I searched a lot on stackoverlfow but most of the answers are about Qt.

​	Perhaps I missed something important? Or must I compile LLVM with source codes rather than using a pre-built one? Could you please introduce some solutions to me?

Thanks a lot!

Best Regards,

Shine

​

**Comment by eliben** [comment]
There's an open PR - https://github.com/eliben/llvm-clang-samples/pull/11 - adding a Makefile for OSX. Maybe that can help. Other than that, I can't really help as I'm not very familiar with building stuff on OSX.
