### ISSUE TITLE
cannot build succefully

### ISSUE THREAD

**Issue by WHUXY** [eliben/llvm-clang-samples#28]
tooling_sample.o: In function `MyASTVisitor::VisitStmt(clang::Stmt*)':
/home/fanl/alpha/build/src/../../src/tooling_sample.cpp:43: undefined reference to`clang::Rewriter::InsertText(clang::SourceLocation, llvm::StringRef, bool, bool)'
/home/fanl/alpha/build/src/../../src/tooling_sample.cpp:48: undefined reference to `clang::Rewriter::InsertText(clang::SourceLocation, llvm::StringRef, bool, bool)'

**Comment by eliben** [comment]
Which LLVM revision / version is that for?
