### ISSUE TITLE
Remove using declarations to improve readability

### ISSUE THREAD

**Issue by Toeger** [eliben/llvm-clang-samples#29]
People look through these samples to see how to use clang as a library, which I believe is the intended purpose. To improve that, code like `clang::ast_matchers::MatchFinder Finder;` would be much more helpful than `MatchFinder Finder;`. Therefore all using declarations should be removed. If that makes the code too long the using declarations should be more specific, so it should be `using clang::ast_matchers::MatchFinder` instead of `using clang::ast_matchers'.

**Comment by eliben** [comment]
Having more specific `using` makes sense. Feel free to submit a PR - I'm traveling right now, though, so it will be a few weeks until I can handle it.

**Comment by eliben** [comment]
Closing for now. Submit a PR if still interested
