### ISSUE TITLE
build failed on 4.0

### ISSUE THREAD

**Issue by intheway** [eliben/llvm-clang-samples#30]
=== Clang 4.0 - branch google/stable ===
Downloaded from https://github.com/llvm-mirror

Included components:
llvm: 008f70d21cc2b33cebd1d4443052e62d3fbea6e8
clang (in llvm/tools/): dad49cdaaa937658428dc79d078dafb2f70e6a4e
libcxx (in llvm/projects): fda3549c01ea0a1d2ee00fe0033c35dc36796fc8 (from clang 3.8)
compiler-rt (in llvm/projects): ee154786652de8fcc302a62fa73e6295cb2af198
openmp (in llvm/projects): 168b27e91b8e3a45a31da1867c910598c93b0348

SHA256(clang-4.0.tar.xz)= 0fe7f0565f6646d5f262daea00d9dae58fd44dc7b073e24707a987b3282c6d47

too many errors.

**Comment by eliben** [comment]
It would help to paste the errors you're seeing.

**Comment by eliben** [comment]
I can't reproduce any problem on my end; all samples build and tests pass vs. LLVM & Clang synced from SVN a few minutes ago.
