### ISSUE TITLE
using-clang-toolchain-samples don't use clang toolchain

### ISSUE THREAD

**Issue by Toeger** [eliben/llvm-clang-samples#32]
In https://github.com/eliben/llvm-clang-samples/blob/master/using_clang_toolchain it says 

> These are samples of using the Clang+LLVM toolchain for building actual executables.

However, none of the samples do any of that. They seem to be test inputs instead.
I would like to see samples that do what described.

**Comment by eliben** [comment]
What do you mean? Did you look at the Makefile?

**Comment by Toeger** [comment]
What I mean is that I expect something like `src_clang/rewritersample.cpp` that produces an executable. The makefile seems to just build the files and create executables, but that means the files belong in `inputs/`.

**Comment by eliben** [comment]
I'm happy with the way things currently are, and the Makefile in that directory *does* use the toolchain, IMHO. If there is a concrete usage you're missing, please open a more targeted issue
