### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by DaoWen** [eliben/llvm-clang-samples#33]
First, I'd like to say that you've done a great public service by making these examples available online. I found your blog posts and the examples in this repository hugely helpful in the process of developing my own LibTooling-based utility.

On that note, also I want to make my custom tool available online, and distribute it along with another open source project as a support tool. However, since this repo doesn't include a License file, I'm not sure how to move forward. (You have a couple files that reference the LLVM license and point to `LICENSE.TXT`, but I don't think that's actually included anywhere in the repo.)

I'm assuming that any files in this repo that don't include an explicit copyright header are your work (e.g., the `Makefile` and most of the examples under `src_clang/`). So, I have two requests:

1. Please grant permission for me to release my source code—which I consider to be a derivative work using your Makefile and some code adapted from your examples—under the [Apache License](https://www.apache.org/licenses/LICENSE-2.0). Your implicit copyright on the examples in this repository will of course be described in the `NOTICE` file.

2. Please add a license agreement to this repository. That should eliminate the need for others to contact you like this in the future when they build on your very useful examples.

If you decide to add a license but you're undecided on which license to use, I'd recommend Apache for this project. If you'd written everything from scratch, something like MIT might be simpler; however, the fact that there are some LLVM-licensed files included makes me think Apache would be a better fit. Apache is still very permissive, but it has that clause requiring redistribution of the `NOTICE` file, which makes it easy for you to include the info about the files that are derived from the LLVM project, and include a copy of the LLVM license in that file as well. (This is the same reason I'm planning to use the Apache license for my project's source code.)

**Comment by eliben** [comment]
The code is in the public domain; I believe it's in the comment header of every source file, is it not?

**Comment by DaoWen** [comment]
Thanks for the clarification! I missed that line in the Makefile. I was expecting something in the Readme explaining the usage rights. The couple examples I happened to be looking at also didn't include the public domain header, so I just assumed it wasn't specified anywhere.

FYI, here's a list of the example source files that don't include any license info in the header:

```
$ git grep -EL "public domain|LICENSE.TXT|LLVM's license" -- *.cpp | grep ^src_
src_clang/experimental/toplevel_decls.cpp
src_clang/experimental/try_matcher.cpp
src_llvm/experimental/loop_info.cpp
```

You might still want to add the LLVM license file somewhere since some files specifically say to look at LICENSE.TXT for the LLVM license details.

Sorry for the confusion, and thanks again for the clarification!

**Comment by eliben** [comment]
Added a LICENSE file and some clarifications in relevant files. Hope this helps
