### ISSUE TITLE
Error on ClangCheck.cpp with clang+llvm-4.0.0

### ISSUE THREAD

**Issue by dohcoex** [eliben/llvm-clang-samples#34]
I used this version _http://releases.llvm.org/4.0.0/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz_
and found the following errors on _ClangCheck.cpp_

**src_clang/ClangCheck.cpp:136:59: error: non-virtual member function marked 'override' hides virtual member function
  bool BeginSourceFileAction(clang::CompilerInstance& CI) override {
                                                          ^
/home/abiy/phd_works/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04/include/clang/Rewrite/Frontend/FrontendActions.h:37:8: note: hidden overloaded virtual function 'clang::FixItAction::BeginSourceFileAction' declared here: different number of parameters (2 vs 1)
  bool BeginSourceFileAction(CompilerInstance &CI,
       ^
src_clang/ClangCheck.cpp:152:53: error: too many arguments to function call, expected 3, have 4
                                    /*DumpLookups=*/false);
                                                    ^~~~~**
I modified the code by removing the _override_ and  _the argument_ errors. It seems to compile correctly.
May be there is some need for update or something I missed ?

**Comment by eliben** [comment]
Did you check out the 4.0 branch of the samples repository when building vs. the 4.0 release?

**Comment by dohcoex** [comment]
No my mistake. It works now when I checked out the llvm4.0 branch. thank you
