### ISSUE TITLE
Problem with basic headers

### ISSUE THREAD

**Issue by hbrunie** [eliben/llvm-clang-samples#35]
Hello,
It is not specific to using your codes, but when I try to run a tool built using
LibTooling Clang library I have an error because it can not find basic headers (cstlib, cstdio ... )

I had the same error just compiling with clang, I just had to put the path after an -isystem option (I put it on .bashrc with an alias to clang, ok it is dirty but it works)
Nevertheless I do not know how to solve this problem with a tool like "rewritersample" for example.
How can I explain to the tool to go look for basic header in som specific path ?

Thank you very much for all this examples up to date !!
Best regards,
 - Hugo

**Comment by eliben** [comment]
Sorry, I can't provide support for Clang/tooling here, just for the code samples
