### ISSUE TITLE
Building with homebrew

### ISSUE THREAD

**Issue by ev1stensberg** [eliben/llvm-clang-samples#39]
Hi! Tried to compile the repo when installing llvm with homebrew. There's a description in the `build_vs_released_binary.sh` file on this, but I'm getting an error when trying to run `make`. It might be due my path not set up properly. Is there any resources on this?

To point out the error, `svn-ninja-release` doesn't exist, haven't installed it either. Using `depot-tools` from Google, and there is where `ninja` lives. 

<img width="564" alt="skjermbilde 2018-05-31 kl 03 53 29" src="https://user-images.githubusercontent.com/16735925/40756923-3346ebf2-6486-11e8-9b11-07b07ff9b34b.png">

**Comment by eliben** [comment]
By default `make` assumes some paths which you likely don't have. I'd recommend using a released version and following instructions in the `Makefile` to set up the paths.
