### ISSUE TITLE
fatal error: 'stddef.h' file not found

### ISSUE THREAD

**Issue by pfsun** [eliben/llvm-clang-samples#7]
Hi Eliben,

You code is very helpful for me. But When I run your tool, there is always one error "fatal error: 'stddef.h' file not found". I check it is builtin includes problem. When I put your tool into the clang binary dir, no error. I want to know how do you solve builtin headers problem.

Thanks.

Best Regards,
Sun

**Comment by eliben** [comment]
I'm not sure this represents a still-existing problem with the latest tools right now. Please open a new issue with more concrete steps if applicable
